@HostAddress = https://localhost:7779
@AppointmentId = 92ad4dab-3e23-478e-835d-e1d44f7c26f8

@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdGllbnRAdGVzdC5jb20iLCJpZCI6IjU0ZTI3ZjUwLTM0ZTYtNDdkMy1hOTJiLTkxYWMyYjMwNDk5YSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBhdGllbnQiLCJleHAiOjE3Njk2MjY5ODgsImlzcyI6Iklubm9DbGluaWMiLCJhdWQiOiJJbm5vQ2xpbmljIn0.vN0_cDYW9_n4u123I7IVmePQB5L-AL0upjoeNZYULas
@DoctorId = d28888e9-2ba9-473a-a40f-e38cb54f9b35
@PatientId = 2ef0dd19-ccfc-4a95-8212-e7e902bc4c48
@OfficeId = 0c87574b-4555-44fc-9160-e7f390c3e552
@ServiceId = 0c87777b-4523-44fc-9160-e7f390c3e552

@StartDateTime = 2025-02-25T14:00:00
@EndDateTime = 2025-02-25T15:00:00


### 1. Создать Appointment
// !TODO: Добавить ошишбку о отсуствии верификации почты
POST {{HostAddress}}/appointments
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "doctorId": "{{DoctorId}}",
  "serviceId": "{{ServiceId}}",
  "officeId": "{{OfficeId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 2. Получить appointment по ID
GET {{HostAddress}}/appointments/{{AppointmentId}}
Accept: application/json


###


### 3. Получить список appointments
GET {{HostAddress}}/appointments
Accept: application/json


### 6. Получить список appointments по doctorId
GET {{HostAddress}}/appointments?doctorId={{DoctorId}}
Accept: application/json


### 7. Обновить appointment
PUT {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "patientId": "{{PatientId}}",
  "doctorId": "{{DoctorId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 8. Удалить appointment
DELETE {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
