@HostAddress = https://localhost:7779
@AppointmentId = 9473e2c9-c13f-447d-a0fb-89674a455ad9

@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdGllbnRAdGVzdC5jb20iLCJpZCI6ImNjOWIyNWNhLTc5YmYtNDE4My04MTM3LTlkMzNiOGE1OGQ3MiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBhdGllbnQiLCJleHAiOjE3Njk2MjgwNTEsImlzcyI6Iklubm9DbGluaWMiLCJhdWQiOiJJbm5vQ2xpbmljIn0.ZQkwmsdKVJQIvlcDBVZ53RMwi_XX2eZD0_pW2R4NYOg
@DoctorId = d28888e9-2ba9-473a-a40f-e38cb54f9b35
@PatientId = cc9b25ca-79bf-4183-8137-9d33b8a58d72
@OfficeId = 0c87574b-4555-44fc-9160-e7f390c3e552
@ServiceId = 0c87777b-4523-44fc-9160-e7f390c3e552

@StartDateTime = 2025-02-25T14:00:00
@EndDateTime = 2025-02-25T15:00:00


### 1. Создать Appointment
// !TODO: Добавить ошишбку о отсуствии верификации почты
POST {{HostAddress}}/appointments
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "doctorId": "{{DoctorId}}",
  "serviceId": "{{ServiceId}}",
  "officeId": "{{OfficeId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 2. Получить appointment по ID
GET {{HostAddress}}/appointments/{{AppointmentId}}
Accept: application/json


###


### 3. Получить список appointments
GET {{HostAddress}}/appointments
Accept: application/json


### 6. Получить список appointments по doctorId
GET {{HostAddress}}/appointments?doctorId={{DoctorId}}
Accept: application/json


### 7. Обновить appointment
PUT {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "patientId": "{{PatientId}}",
  "doctorId": "{{DoctorId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 8. Удалить appointment
DELETE {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
