@HostAddress = https://localhost:7779
@AppointmentId = f46de88c-4289-4bc2-bd66-7dab84dba1fa

@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdGllbnRAdGVzdC5jb20iLCJpZCI6IjJjM2I1NzRhLTI5MWQtNDBiZi1iYmMyLWRlYTc2Njk4MzFjMiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlBhdGllbnQiLCJleHAiOjE3NzA2NDcxODIsImlzcyI6Iklubm9DbGluaWMiLCJhdWQiOiJJbm5vQ2xpbmljIn0.r0rwZviM2JPrcjVQZbuMq4_JaiiiqiNmiRdMGz_BjSo
@DoctorId = d28888e9-2ba9-473a-a40f-e38cb54f9b35
@PatientId = 2c3b574a-291d-40bf-bbc2-dea7669831c
@OfficeId = 0c87574b-4555-44fc-9160-e7f390c3e552
@ServiceId = 0c87777b-4523-44fc-9160-e7f390c3e552

@StartDateTime = 2025-02-25T14:00:00
@EndDateTime = 2025-02-25T15:00:00


### 1. Создать Appointment
// !TODO: Добавить ошишбку о отсуствии верификации почты
POST {{HostAddress}}/appointments
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "doctorId": "{{DoctorId}}",
  "serviceId": "{{ServiceId}}",
  "officeId": "{{OfficeId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 2. Получить appointment по ID
GET {{HostAddress}}/appointments/{{AppointmentId}}
Accept: application/json


###


### 3. Получить список appointments
GET {{HostAddress}}/appointments
Accept: application/json


### 6. Получить список appointments по doctorId
GET {{HostAddress}}/appointments?doctorId={{DoctorId}}
Accept: application/json


### 7. Обновить appointment
PUT {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "patientId": "{{PatientId}}",
  "doctorId": "{{DoctorId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 8. Удалить appointment
DELETE {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
