//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Identity.Domain {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Identity.Domain.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Account_AlreadyExists {
            get {
                return ResourceManager.GetString("Account_AlreadyExists", resourceCulture);
            }
        }
        
        internal static string Account_NotFound {
            get {
                return ResourceManager.GetString("Account_NotFound", resourceCulture);
            }
        }
        
        internal static string Email_Empty {
            get {
                return ResourceManager.GetString("Email_Empty", resourceCulture);
            }
        }
        
        internal static string Email_InvalidFormat {
            get {
                return ResourceManager.GetString("Email_InvalidFormat", resourceCulture);
            }
        }
        
        internal static string Email_TooLong {
            get {
                return ResourceManager.GetString("Email_TooLong", resourceCulture);
            }
        }
        
        internal static string Password_TooWeak {
            get {
                return ResourceManager.GetString("Password_TooWeak", resourceCulture);
            }
        }
        
        internal static string Account_Inactive {
            get {
                return ResourceManager.GetString("Account_Inactive", resourceCulture);
            }
        }
        
        internal static string PhoneNumber_Invalid {
            get {
                return ResourceManager.GetString("PhoneNumber_Invalid", resourceCulture);
            }
        }
        
        internal static string PhoneNumber_WrongCountry {
            get {
                return ResourceManager.GetString("PhoneNumber_WrongCountry", resourceCulture);
            }
        }
        
        internal static string PhoneNumber_ParseError {
            get {
                return ResourceManager.GetString("PhoneNumber_ParseError", resourceCulture);
            }
        }
    }
}