@HostAddress = https://localhost:7779
@AppointmentId = 90ddf14b-cb3e-4bb7-b8e3-7d44b8ff54b6

@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdGllbnQyQHRlc3QuY29tIiwiaWQiOiIwN2M4NjAyZC01NTc2LTQ4Y2EtYTVmYi00N2ViNzIxNDE0ZGIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJQYXRpZW50IiwiZXhwIjoxNzcwODA4MjExLCJpc3MiOiJJbm5vQ2xpbmljIiwiYXVkIjoiSW5ub0NsaW5pYyJ9.JBklnMDmL3GCjXrGNlLtXIyMTTeGoCy8bzM1weMMEsw
@DoctorId = d28888e9-2ba9-473a-a40f-e38cb54f9b35
@PatientId = 2c3b574a-291d-40bf-bbc2-dea7669831c
@OfficeId = 0c87574b-4555-44fc-9160-e7f390c3e552
@ServiceId = 0c87777b-4523-44fc-9160-e7f390c3e552

@StartDateTime = 2025-02-25T14:00:00
@EndDateTime = 2025-02-25T15:00:00


### 1. Создать Appointment
// !TODO: Добавить ошишбку о отсуствии верификации почты
POST {{HostAddress}}/appointments
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "doctorId": "{{DoctorId}}",
  "serviceId": "{{ServiceId}}",
  "officeId": "{{OfficeId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 2. Получить appointment по ID
GET {{HostAddress}}/appointments/{{AppointmentId}}
Accept: application/json


###


### 3. Получить список appointments
GET {{HostAddress}}/appointments
Accept: application/json


### 6. Получить список appointments по doctorId
GET {{HostAddress}}/appointments?doctorId={{DoctorId}}
Accept: application/json


### 7. Обновить appointment
PUT {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "patientId": "{{PatientId}}",
  "doctorId": "{{DoctorId}}",
  "startDateTime": "{{StartDateTime}}",
  "endDateTime": "{{EndDateTime}}"
}


###


### 8. Удалить appointment
DELETE {{HostAddress}}/appointments/{{AppointmentId}}
Authorization: Bearer {{Token}}


полно-ТЕкстовый индекс или contains
