// <auto-generated />
using System;
using System.Collections.Generic;
using Appointment.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Appointment.Api.Data.Migrations
{
    [DbContext(typeof(AppointmentDbContext))]
    [Migration("20260813122014_ResyncAppointmentsView")]
    partial class ResyncAppointmentsView
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("appointment")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Appointment.Api.Data.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Duration", "Appointment.Api.Data.Appointment.Duration#TimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("End")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("duration_end");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("duration_start");
                        });

                    b.HasKey("Id");

                    b.ToTable("appointments", "appointment");
                });

            modelBuilder.Entity("Appointment.Api.Data.AppointmentView", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("DoctorFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_first_name");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("DoctorLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_last_name");

                    b.Property<string>("DoctorMiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doctor_middle_name");

                    b.Property<DateTimeOffset>("DurationEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duration_end");

                    b.Property<DateTimeOffset>("DurationStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("duration_start");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("is_approved");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date")
                        .HasColumnName("local_date");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("office_address");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uuid")
                        .HasColumnName("office_id");

                    b.Property<string>("PatientFirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_first_name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PatientLastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_last_name");

                    b.Property<string>("PatientMiddleName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_middle_name");

                    b.Property<string>("PatientPhone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patient_phone");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_name");

                    b.ToTable((string)null);

                    b.ToView("appointments_view", "appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
