<Project Sdk="Aspire.AppHost.Sdk/13.1.2">
  <ItemGroup>
    <ProjectReference Include="..\InnoClinic.Appointment\src\Appointment.Api\Appointment.Api.csproj" />
    <ProjectReference Include="..\InnoClinic.Identity\src\Identity.Api\Identity.Api.csproj" />
    <ProjectReference Include="..\InnoClinic.ClinicManagement\src\ClinicManagement.Api\ClinicManagement.Api.csproj" />
    <ProjectReference Include="..\InnoClinic.Profile\src\Profile.Api\Profile.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MailPit" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9399b61e-953c-4d38-bb58-38f6b6fba842</UserSecretsId>
  </PropertyGroup>
</Project>